In [1]:
import pandas as pd
from scipy.stats import chi2_contingency, ttest_ind

In [2]:
# Load the insurance data
file_path ='../data/MachineLearningRating_v3.txt'
data = pd.read_csv(file_path, sep='|', low_memory=False)
data.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [11]:
# Risk differences across provinces (categorical data)
contingency_table = pd.crosstab(data['Province'], data['CoverCategory'])
chi2, p_value, _, _ = chi2_contingency(contingency_table)
if p_value < 0.05:
    print("Reject null hypothesis: Risk differences exist across provinces.")
else:
    print("Fail to reject null hypothesis: No significant risk differences.")

 #Profit differences between zip codes (numerical data)
group_a = data[data["MaritalStatus"] == "A"]
group_b = data[data["MaritalStatus"] == "B"]
t_statistic, p_value = ttest_ind(group_a['TotalPremium'], group_b['TotalPremium'])
if p_value < 0.05:
    print("Reject null hypothesis: Significant profit differences between zip codes.")
else:
    print("Fail to reject null hypothesis: No significant TotalPremium differences.")

Reject null hypothesis: Risk differences exist across provinces.
Fail to reject null hypothesis: No significant TotalPremium differences.

In [24]:
import pandas as pd
from scipy.stats import chi2_contingency

women_data = data[data['Gender'] == 'Female']
men_data = data[data['Gender'] == 'Male']

# Check if there is data in both women and men dataframes
if not women_data.empty and not men_data.empty:
    chi2_gender, p_value_gender, _, _ = chi2_contingency(pd.crosstab(women_data['Product'], men_data['Product']))
    if p_value_gender < 0.05:
        print("Reject null hypothesis: Significant risk differences between women and men.")
    else:
        print("Fail to reject null hypothesis: No significant risk differences between women and men.")
else:
    print("Data is missing for either women or men, please check the data.")

ValueError: No data; `observed` has size 0.